electronic_signature: Allow to bypass electronic signature process
coopengo/trytond_electronic_signature pull request #16
Opened 2021-11-25 14:01 UTC by romainseon

Fix #21184

2021-11-25 15:16 UTC, jmousset approved these changes
ok, par contre il me semble qu'il faut déclarer le button en xml pour que les tests passent

2021-11-25 15:37 UTC, JCavallo requested changes
Pas trop vu le rapport avec la fiche par contre

2021-11-25 15:37 UTC, JCavallo commented on attachment.py
> +                    'invisible': ~Eval('can_force_signature')}
Style : "," en fin de ligne

```suggestion
                    'invisible': ~Eval('can_force_signature')},
```

2021-11-25 15:37 UTC, JCavallo commented on attachment.py
> +        Signature.manually_force([a.signature for a in attachments])
un attachment peut avoir plusieurs signatures non ? ou c'est un O2M limité à 1 ? Plutôt utiliser le O2M que le champ fonction

2021-11-25 15:37 UTC, JCavallo commented on signature.py
> +            states={'invisible': Eval('status') != 'manually_forced'},
required si le status est "manually_forced" je pense

2021-11-25 15:37 UTC, JCavallo commented on signature.py
> +        return self.write_uid.id if self.write_uid else self.create_uid.id
Ca devrait être un vrai champ, en soit il peut y avoir une modif post forçage

2021-11-26 13:52 UTC, nidhalk approved these changes

2021-12-01 16:59 UTC, romainseon commented on attachment.py
> +        Signature.manually_force([a.signature for a in attachments])
il ne peut y avoir qu'une seule signature active à un moment donné, c'est ce que calcule le champ fonction

2021-12-01 17:00 UTC, romainseon commented on signature.py
> +            states={'invisible': Eval('status') != 'manually_forced'},
euh... c'est un champ fonction qui ne présente que le last_user (qui est forcément celui qui a bypassé puisque le process est terminé par la suite)

2021-12-01 17:00 UTC, romainseon commented on signature.py
> +        return self.write_uid.id if self.write_uid else self.create_uid.id
non ce n'est pas possible

2021-12-01 17:00 UTC, romainseon commented
> Pas trop vu le rapport avec la fiche par contre

Pas trop vu le rapport avec ton commentaire.

2021-12-01 17:04 UTC, JCavallo commented
https://support.coopengo.com/issues/21184 => Evolution_modification coordonnées bancaires (courriers + date d'effet)

2021-12-01 17:06 UTC, JCavallo commented on signature.py
> +        return self.write_uid.id if self.write_uid else self.create_uid.id
Pour l'instant. On risque de casser ça si on rajoute un truc plus tard, sans s'en rendre compte, et en cassant une trace d'audit

2021-12-15 18:56 UTC, JCavallo approved these changes
Pas sûr du champ forced_by, on verra bien

2022-02-14 09:41 UTC, merged